services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-standalone-lab3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  service-a:
    build:
      context: ./services/service-a
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:15672

  service-b:
    build:
      context: ./services/service-b
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:15672